[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "ch_title_gen"
version = "1.2"
requires-python = ">=3.10"
dependencies = ["pycnnum==2.1.1"]
description = "A program that changes chinese tv show titles to english format."
